# The URL the site will be built for
base_url = "https://blog.dpanovitch.dev"

title = "Demetrius's Blog"

description = "My personal blog and portfolio. Built using Zola."

default_language = "en"

output_dir = "public"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author_name = "Demetrius Panovitch"
keywords = "Portfolio, Blog, Computer Science"
seo = true
banner = "images/avatar.jpeg"

[extra.social]
feed = true
mail = "demetrius.mp789@gmail.com"
linkedin = "demetrius-panovitch"
github = "demetrius-mp"
stack = "12002242/demetrius-mp"
twitch = "demetriuspanovitch"
youtube = "channel/UC2sdf64vEwmBlI_ZwdNauEQ"