# The URL the site will be built for
base_url = "https://blog.dpanovitch.dev"
title = "Demetrius's Blog"
description = "My personal blog and portfolio. Built using Zola."
default_language = "en"
output_dir = "public"
compile_sass = false
build_search_index = false
taxonomies = [
    { name = "tags", feed = true }
]

[markdown]
highlight_code = true
highlight_theme = "material-dark"

[extra]
author_name = "Demetrius Panovitch"
keywords = "Portfolio, Blog, Computer Science"
profile_picture = "images/avatar.jpeg"
identity_phrase = "Moved by curiosity."
interests = ["Data Science", "Backend", "Developer Experience", "Open Source"]

[[extra.education.courses]]
name = "Msc. in Computer Science"
dates = "2022-today"
institution  = "FACOM, UFMS"

[[extra.education.courses]]
name = "Bachelor in Software Engineering"
dates = "2019-2022"
institution  = "FACOM, UFMS"

[extra.social]
feed = true
mail = "demetrius.mp789@gmail.com"
linkedin = "demetrius-panovitch"
github = "demetrius-mp"
stack = "12002242/demetrius-mp"
twitch = "demetriuspanovitch"
youtube = "channel/UC2sdf64vEwmBlI_ZwdNauEQ"